### PR TITLE
Security update

### PR DESCRIPTION
**Pull request by jrhorn424**
Other warnings are not addressable right now. They require investigation into versioning constraints.

### CODE REVIEW

**Comment by jrhorn424** [comment]
@drobbins Do we want to keep the "minor changes" commit and push it into production?

**Comment by drobbins** [comment]
1. I'm OK updating Bundler but it probably doesn't matter too much. I've since removed 2.1.4 from my machine and amended that commit to not have the Gemfile.lock change.
2. I'm not enough of a Rail's person to know if the `protect_from_forgery` function calls are significant.
3. Same as 2 for the honeybadger.yml file. If we're not going to use it can we remove it all together rather than that weird way of editing the file?

I don't consider any those changes to be security related, except maybe those in 2.

**Comment by jrhorn424** [comment]
1. Feels like a chore, but would be nice to stay up-to-date.
1. Those calls are already present in the ApplicationController:
1. If you use the credentials I created (I'm happy to share them) and the committed, encrypted configuration files that I have on a branch somewhere, we don't even need the edit to the honeybadger.yml file anymore! :)

**Comment by drobbins** [comment]
1. I'm totally fine with just updating it.
2. I just tested the production branch without those changes and was able to start it fine, so I think we can just toss them unless there is a reason to keep.
3. Without the change in 3 I get (and similar for the web.1 thread):
    ```
    drobbins at 3200-C02ST96KGTFL in national-fever-tracker on production
    $ foreman start
    09:12:51 web.1     | started with pid 20842
    09:12:51 webpack.1 | started with pid 20843
    09:12:51 worker.1  | started with pid 20844
    ...
    09:13:49 worker.1  | undefined method `[]' for nil:NilClass
    09:13:49 worker.1  | /Users/drobbins/Desktop/NoCloud/projects/national-fever-tracker/config/honeybadger.yml:2:in `<main>'
    09:13:49 worker.1  | /usr/local/Cellar/ruby/2.7.1/lib/ruby/2.7.0/erb.rb:905:in `eval'
    09:13:49 worker.1  | /usr/local/Cellar/ruby/2.7.1/lib/ruby/2.7.0/erb.rb:905:in `result'
    09:13:49 web.1     | Exiting
    09:13:49 worker.1  | /usr/local/lib/ruby/gems/2.7.0/gems/honeybadger-4.6.0/lib/honeybadger/config/yaml.rb:29:in `load_yaml'
    ...
    09:13:50 worker.1  | exited with code 1
    09:13:50 system    | sending SIGTERM to all processes
    ```
    If there is a better way to solve the problem (such as using your config files) I'm all for it.

**Comment by jrhorn424** [comment]
Do we want to have the changes for (3) done in a separate PR? After that PR, we should have less git-fu to worry about during development.

**Comment by drobbins** [comment]
Did I understand that you don't need the change in (3) when you work locally?

**Comment by jrhorn424** [comment]
That's right. I have a branch with fixed credentials. It's over on Lenny's repo if you want to have a look. I can do the same thing here. I start new features from that branch,  then when ready to PR, I perform git-fu to obtain a clean diff. Very unwieldy.

**Comment by drobbins** [comment]
I've been doing the same: developing on a feature branch and the rebasing it onto production minus my local mods.

**Pull request merged**
