### PR TITLE
Adding bios of new team members

### PR DESCRIPTION
**Pull request by joybuchanan**
Joy saved images of new team members, but Joy does not know how to insert them into this page or save them to our server, so they have been left out for now.

### CODE REVIEW

**Comment by jrhorn424** [comment]
Hey folks. We have two PRs for @free-soellingeraj's bio, not sure which should be merged first. Then maybe merge this one? Additionally, are we merging to `master` and then to `production`?

**Comment by joybuchanan** [comment]
I shorted the bios of me and Aaron and Lenny ( a bit ) and then I added new short bios for new team members. Aaron is no longer at that previous position, so I think the short one is the way to go. "data scientist"

**Comment by free-soellingeraj** [comment]
Thanks, that's fine.
--aaron

**Comment by jrhorn424** [comment]
@drobbins You mentioned that you backfilled, but I'm seeing my map changes in this PR. Is this because we switched repos, and if so, do I need to go grab a commit from over there?

**Pull request merged**
